// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "email", type: "text" },
      { name: "name", type: "text" },
    ],
  },
  {
    name: "questions-completed",
    columns: [
      { name: "userid", type: "text" },
      { name: "userquestion", type: "text" },
      { name: "completed", type: "bool" },
      { name: "upvote", type: "bool" },
      { name: "downvote", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type QuestionsCompleted = InferredTypes["questions-completed"];
export type QuestionsCompletedRecord = QuestionsCompleted & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  "questions-completed": QuestionsCompletedRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Guido1Alessandro1Trevisan-s-workspace-ic2bsb.us-east-1.xata.sh/db/coach-quant",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
